
spring:
  profiles: dev
  h2:
    console:
      path: /h2
      enabled: true
---
spring:
  profiles: qa
  h2:
    console:
      path: /h2
      enabled: true
---
spring:
  profiles: uat
  h2:
    console:
      path: /h2
      enabled: true
---
spring:
  profiles: prod
  h2:
    console:
      path: /h2
      enabled: true
---
spring:
  profiles: test
  h2:
    console:
      path: /h2
      enabled: true
---